In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.svm import SVC

In [ ]:
train_data=pd.read_csv("train (1).csv") 

In [ ]:
train_data.head()

ID  Sales  CompetitorPrice  Income  Advertising  Population  Price  \
0   1   6.01              131      29           11         335    127   
1   2   6.50              148      51           16         148    150   
2   3   7.70              118      71           12          44     89   
3   4   7.78               86      54            0         497     64   
4   5  11.82              113      66           16         322     74   

  Location  Age  Education Urban   US  
0      Bad   33         12   Yes  Yes  
1   Medium   58         17    No  Yes  
2   Medium   67         18    No  Yes  
3      Bad   33         12   Yes   No  
4     Good   76         15   Yes  Yes

In [ ]:
le=LabelEncoder()
for i in ['Location','Urban','US']:
  train_data[i]=le.fit_transform(train_data[i])

In [ ]:
train_data.isnull().sum()

ID                 0
Sales              0
CompetitorPrice    0
Income             0
Advertising        0
Population         0
Price              0
Location           0
Age                0
Education          0
Urban              0
US                 0
dtype: int64

In [ ]:
min(train_data['Sales'])

0.0

In [ ]:
train_data.head()

ID  Sales  CompetitorPrice  Income  Advertising  Population  Price  \
0   1   6.01              131      29           11         335    127   
1   2   6.50              148      51           16         148    150   
2   3   7.70              118      71           12          44     89   
3   4   7.78               86      54            0         497     64   
4   5  11.82              113      66           16         322     74   

   Location  Age  Education  Urban  US  
0         0   33         12      1   1  
1         2   58         17      0   1  
2         2   67         18      0   1  
3         0   33         12      1   0  
4         1   76         15      1   1

In [ ]:
y=pd.cut(train_data.Sales,bins=[0,5,10,50],labels=[1,2,3],include_lowest=True)

In [ ]:
x=train_data.drop(['Sales','ID'],axis=1)

In [ ]:
display(x)

CompetitorPrice  Income  Advertising  Population  Price  Location  Age  \
0                131      29           11         335    127         0   33   
1                148      51           16         148    150         2   58   
2                118      71           12          44     89         2   67   
3                 86      54            0         497     64         0   33   
4                113      66           16         322     74         1   76   
..               ...     ...          ...         ...    ...       ...  ...   
344              138      61           12         156    120         2   25   
345              130      58           19         366    139         0   33   
346              144      69           11         131    104         2   47   
347              129      76           16          58    121         2   69   
348              121      42            4         188    118         2   54   

     Education  Urban  US  
0           12      1   1  
1           17      0   1  
2           18      0   1  
3           12      1   0  
4           15      1   1  
..         ...    ...  ..  
344         14      1   1  
345         16      1   1  
346         11      1   1  
347         12      1   1  
348         15      1   1  

[349 rows x 10 columns]

In [ ]:
display(y)

0      2
1      2
2      2
3      2
4      3
      ..
344    2
345    2
346    3
347    2
348    2
Name: Sales, Length: 349, dtype: category
Categories (3, int64): [1 < 2 < 3]

In [ ]:
x.isnull().sum()

CompetitorPrice    0
Income             0
Advertising        0
Population         0
Price              0
Location           0
Age                0
Education          0
Urban              0
US                 0
dtype: int64

In [ ]:
model=SVC(kernel='linear')

In [ ]:
model.fit(x,y)

SVC(kernel='linear')

In [ ]:
test_data=pd.read_csv("test (1).csv")

In [ ]:
for i in ['Location','Urban','US']:
  test_data[i]=le.fit_transform(test_data[i])

In [ ]:
test_data.head()

ID  Sales  CompetitorPrice  Income  Advertising  Population  Price  \
0   1   6.39              131      21            8         220    171   
1   2   8.77              118      86            7         265    114   
2   3   6.89              129      69           10         289    110   
3   4   7.96              157      53            0         403    124   
4   5   7.57              112      88            2         243     99   

   Location  Age  Education  Urban  US  
0         1   29         14      1   1  
1         1   52         15      0   1  
2         2   50         16      0   1  
3         0   58         16      1   0  
4         2   62         11      1   1

In [ ]:
x_test=test_data.drop(['Sales','ID'],axis=1)

In [ ]:
x_test.head()

CompetitorPrice  Income  Advertising  Population  Price  Location  Age  \
0              131      21            8         220    171         1   29   
1              118      86            7         265    114         1   52   
2              129      69           10         289    110         2   50   
3              157      53            0         403    124         0   58   
4              112      88            2         243     99         2   62   

   Education  Urban  US  
0         14      1   1  
1         15      0   1  
2         16      0   1  
3         16      1   0  
4         11      1   1

In [ ]:
y_test=pd.cut(test_data.Sales,bins=[0,5,10,50],labels=[1,2,3],include_lowest=True)

In [ ]:
y_test

0     2
1     2
2     2
3     2
4     2
5     2
6     2
7     2
8     2
9     2
10    2
11    3
12    3
13    2
14    1
15    3
16    1
17    2
18    3
19    3
20    3
21    1
22    3
23    2
24    3
25    1
26    1
27    1
28    1
29    2
30    3
31    2
32    2
33    2
34    2
35    2
36    2
37    3
38    2
39    1
40    1
41    2
42    2
43    2
44    2
45    1
46    1
47    3
48    2
49    2
50    2
Name: Sales, dtype: category
Categories (3, int64): [1 < 2 < 3]

In [ ]:
ypred=model.predict(x_test)

In [ ]:
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

In [ ]:
print(classification_report(ypred,y_test))

              precision    recall  f1-score   support

           1       0.73      0.57      0.64        14
           2       0.76      0.73      0.75        30
           3       0.55      0.86      0.67         7

    accuracy                           0.71        51
   macro avg       0.68      0.72      0.68        51
weighted avg       0.72      0.71      0.71        51



In [ ]:
print(accuracy_score(ypred,y_test))

0.7058823529411765


In [ ]:
print(confusion_matrix(ypred,y_test))

[[ 8  6  0]
 [ 3 22  5]
 [ 0  1  6]]
